name: Rotate Fly.io App Region

on:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allows manual triggering

env:
  node_version: 19
  FORCE_COLOR: 1

concurrency: # prevent concurrent releases
  group: flyctl-roll-region
  cancel-in-progress: true

jobs:
  rotate-region:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Run Rotate Region Script
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: ./scripts/rotate-region.sh
